services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: >
        sh -c "
          php artisan migrate --force &&
          php artisan db:seed
        "
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ymaps_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: php artisan serve --host=0.0.0.0 --port=8000 --no-reload

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ymaps_queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: php artisan queue:work --verbose --timeout=300

  vite:
    image: node:22-alpine
    container_name: ymaps_vite
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    environment:
      - CI=true
      - LARAVEL_BYPASS_ENV_CHECK=1
    command: ["sh", "-c", "npm i -g pnpm@latest && pnpm install && pnpm dev --host"]


  db:
    image: postgres:16-alpine
    container_name: ymaps_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ymaps
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ymaps"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
